package org.totalboumboum.ai.v200910.ais.demirciduzokergok.v1;

public enum Cas {
	BOMBE, LIBRE, ENNEMIE, DESTRUCTIBLE_MUR, INDESTRUCTIBLE_MUR, FEU, FEURANGE, BOMBERMAN, BONUSFEU, BONUSBOMBE, DANGER, MALUS, BOMBE_IMAGINAIRE
}
