package tournament200910.demirciduzokergok;

public enum Cas {
	BOMBE, LIBRE, ENNEMIE, DESTRUCTIBLE_MUR, INDESTRUCTIBLE_MUR, FEU, FEURANGE, BOMBERMAN, BONUSFEU, BONUSBOMBE, DANGER, MALUS, BOMBE_IMAGINAIRE
}
