#!/bin/bash
# -------------------------------------------------------------------
#
# This is a BASH (Bourne-Again SHell) script, 
# it should work on most Linux, Unix, and Mac OS.
# It launches TBB with the appropriate parameters
#
# -------------------------------------------------------------------
#
# define path variables
	ai="./resources/ai"
	bin="./bin"
	jdom="./resources/lib/jdom.jar"
	cp="${bin}:${jdom}:${ai}"
	launcher="fr.free.totalboumboum.QuickLauncher"
#
# launch the game
	java -Xmx128m -classpath $cp $launcher
#
#
