package org.totalboumboum.ai.v200809.ais.erisikpektas.v2c;

public enum Etat {
	 INDESTRUCTIBLES,FEU,FLAMMES,BOMBE,DESTRUCTIBLES,LIBRE,ADVERSAIRE,POINT,BOMBEPOSS,FLAMMESPOSS,DANGER,BOMBEDANGER, POINTFLAMMES,FEUFLAMMES
		

}
