package tournament200910.calisirguner.v4;

//pour map
public enum Etat {
	INDESTRUCTIBLES, FEU, FLAMMES, BOMBE, DESTRUCTIBLES, LIBRE, ADVERSAIRE, POINT, INACCESSIBLE, ACCESSIBLE, BOMBEPOSS, FLAMMESPOSS, DANGER, NOUS

}
