package tournament200809.erisikpektas.v2;

public enum Etat {
	 INDESTRUCTIBLES,FEU,FLAMMES,BOMBE,DESTRUCTIBLES,LIBRE,ADVERSAIRE,POINT,BOMBEPOSS,FLAMMESPOSS,DANGER,BOMBEDANGER, POINTFLAMMES,FEUFLAMMES
		

}
