package tournament200809.medeniuluer.v2;

public enum ZoneEnum {
	CARACTERE,RIVAL,BOMBE,FEUPOSSIBLE,FEU,BONUSFEU,BONUSBOMBE,BLOCDESTRUCTIBLE,BLOCINDESTRUCTIBLE,LIBRE,
	FEUPOSSIBLE_TRESDANGEREUX,FEUPOSSIBLE_DANGEREUX,FEUPOSSIBLE_PEUDANGEREUX,FEUPOSSIBLE_PASDANGEREUX,
	REGION_HERO,REGION_RIVAL,EXPLOSION_SIMULE,BLOC_EXPLOSE_SIMULE

}
