package tournament200809.tirtiltomruk.zone;

public enum ZoneEnum {
	CARACTERE,RIVAL,BOMBE,FEUPOSSIBLE,FEU,BONUSFEU,BONUSBOMBE,BLOCDEST,BLOCINDEST,LIBRE,
	FEUPOSSIBLE_TRESDANGEREUX,FEUPOSSIBLE_DANGEREUX,FEUPOSSIBLE_PEUDANGEREUX,FEUPOSSIBLE_PASDANGEREUX,
	REGION_HERO,REGION_RIVAL,EXPLOSION_SIMULE,BLOC_EXPLOSE_SIMULE
}
