package tournament200809v2.kokciyanmazmanoglu;

public enum Mission {

	STAND_IDLY,
	ATTACK_RIVAL,
	DESTROY_WALL,
	GATHER_EXTRA_BOMB,
	GATHER_RANGE_EXTENDER,
	DESTROY_SURPLUS_BOMB,
	DESTROY_SURPLUS_RANGE_EXTENDER,
	RUN_RUN_RUN_FAR_AWAY;
	
}
