package tournament200809v2.erisikpektas;

public enum Etat {
	 INDESTRUCTIBLES,FEU,FLAMMES,BOMBE,DESTRUCTIBLES,LIBRE,ADVERSAIRE,POINT,BOMBEPOSS,FLAMMESPOSS,DANGER,BOMBEDANGER, POINTFLAMMES,FEUFLAMMES
		

}
