package org.totalboumboum.ai.v200809.ais.medeniuluer.v2c;

/**
*
* @author Ekin Medeni
* @author Pinar Uluer
*
*/
public enum ZoneEnum {
	CARACTERE,RIVAL,BOMBE,FEUPOSSIBLE,FEU,BONUSFEU,BONUSBOMBE,BLOCDESTRUCTIBLE,BLOCINDESTRUCTIBLE,LIBRE,
	FEUPOSSIBLE_TRESDANGEREUX,FEUPOSSIBLE_DANGEREUX,FEUPOSSIBLE_PEUDANGEREUX,FEUPOSSIBLE_PASDANGEREUX,
	REGION_HERO,REGION_RIVAL,EXPLOSION_SIMULE,BLOC_EXPLOSE_SIMULE

}
