#!/bin/bash
# -------------------------------------------------------------------
#
# This is a BASH (Bourne-Again SHell) script, 
# it should work on most Linux, Unix, and Mac OS.
# It (re)compiles the whole TBB game
#
# -------------------------------------------------------------------
#
# define path variables
	main="./src/fr/free/totalboumboum"
	aig=${main}/ai
	ai="./resources/ai"
	bin="./bin"
	jdom="./resources/lib/jdom.jar"
	cp="${bin}:${jdom}"
	sp="./src"
#
# create directory for .class files
	if [ -d $bin ]; then
		echo "${bin} already exists"
	else
		mkdir $bin
	fi	
#
# (re)compile the game
	echo "compiling the game..."
	javac -nowarn -sourcepath $sp -classpath $cp ${main}/Launcher.java ${main}/QuickLauncher.java -d $bin
# (re)compile the AI classes located in the game
	echo "compiling the AI classes inside the game..."
	for i in $(ls -d ${aig}/*/); do 
		echo -e "\t${i}"	
		javac -nowarn -sourcepath $sp -classpath $cp $i/*.java -d $bin
	done
#
# (re)compile the AI classes located in resources/ai
	echo "compiling the AI classes located in the resources..."
	for i in $(ls -d ${ai}/*/); do
		echo -e "\t${i}"
		for j in $(ls -d $i*/); do
			echo -e "\t\t${j}"	
			javac -nowarn -sourcepath ${sp}:${ai} -classpath ${cp}:${ai} $j/*.java
		done
	done
#
#
